[dependencies]

[package]
authors = ["Lukas Grassauer <lukas@grassauer.eu>"]
description = "An assistant for mundane tasks."
edition = "2021"
license = "MIT"
name = "ass-rs"
readme = "README.md"
version = "0.0.0"
